### ISSUE TITLE
Performanceoptimierung AlleGruppenAbrufen

### ISSUE THREAD

**Issue by philippst** [atddo/BdPMVApp#23]
Der initiale Aufruf der App ist bei Nutzern mit weitergehenden Berechtigungen (Landes- und Bundesebene) ziemlich langsam. Ursächlich ist vermutlich die rekursive Abfrage der Gruppierungsstruktur:

https://github.com/pfadfinden/BdPMVApp/blob/9316801c535229a41f6e2333f0d16e863b86e997/BdP%20MV/BdP_MV/Services/Group_Control.cs#L21-L36

Leider ist das aktuell nicht über die API anders möglich. Folgende beide Verbesserungsvorschläge hätte ich hierfür aber:

- Nur Gruppierungen deren Namen auf `00` endet, dürfen laut MV Konvention Untergruppierungen haben. Wenn Name also nicht auf `00` endet, kann man sich den rekursiven Aufruf sparen. -> reduziert Anzahl der Requests deutlich
- Gruppierungen die mit der Bezeichnung `zzz` sind nicht mehr relevant und können eigentlich ignoriert werden -> reduziert Anzahl der Requests ein wenig

Beispielimplementierung hier für Java zu finden: 
https://github.com/pfadfinden/ica-services/blob/2927cb4e93074939918b6b2c1b32c6b9305cdeb2/src/main/java/de/pfadfinden/ica/service/GruppierungService.java#L158

**Comment by atddo** [comment]
Danke für die Info, da das nirgends dokumentiert ist, konnte ich da auch nicht drauf eingehen. 
Am allerschönsten wäre es, wenn der Hersteller ein JSON File mit der gesamten Baumstruktur in der API ausliefern könnte. 
Auch hatten @guschtl  und ich ein lokales Caching angedacht... Das würde heißen, dass das Objekt serialisiert auf dem Smartphone abgelegt wird und alle 30 Tage oder auf Anfrage neu generiert wird. In ersten, lokalen Tests ist ein großer Performancegewinn zu erziehlen. Es wird da ja nur der  Gruppenbaum mit id, Name und "Kinder-Gruppen" gespeichert also nichts personenbezogenes. Auch ändern sich die Gruppen ja nicht jede Woche ;-)
Was hältst du von dem Ansatz @philippst - gerne auch kombiniert mit der Abfrage ob eine Gruppe auf 00 endet...

**Comment by philippst** [comment]
Das Thema Gruppierungsbaum via API habe ich tatsächlich auf unserem Backlog für den Hersteller, aber hier noch keine Ahnung ob und wann soetwas realisierbar ist. Würde ja auch für die offizielle MV Oberfläche eine Reduktion unnötiger Requests darstellen.

Gegen den geschilderten Cache Ansatz des Gruppierungsbaums spricht aus meiner Sicht nichts. Selbst in dem Fall, dass jemanden die Berechtigung für eine Gruppierung entzogen wird, würde er halt einfach solange die Gruppierung weiterhin, aber ohne Mitgliedern sehen. Aber schon allein durch die Vermeidung der 00-Gruppen Requests sparst du dir ein paar Hundert Requests ...

**Comment by atddo** [comment]
Ich hab das Caching wieder ausgebaut... Das war nur fehlerbehaftet und man hätte ganz viele Sonderfälle abdecken müssen (teilen eines Geräts von mehreren MV Nutzern; Tablet in Pfadfinderfamilie, was auch immer)... Der 00 - Filter sollte da einiges an Performance bringen.
