### ISSUE TITLE
Nutzung HttpClient in APIConnector

### ISSUE THREAD

**Issue by philippst** [atddo/BdPMVApp#29]
Hallo @atddo ,

ich habe mal noch einen Verbesserungsvorschlag für den MVConnector. Anstatt dort nativ mit einem `HttpWebRequest` wäre es glaube ich deutlich schöner, wie auch im C# Manual beschrieben, hier die `HttpClient` Klasse zu nutzen.
 https://github.com/pfadfinden/BdPMVApp/blob/master/BdP%20MV/BdP_MV/Services/MVConnector.cs

Für Details siehe hier: https://docs.microsoft.com/de-de/dotnet/api/system.net.http.httpclient?view=netframework-4.8

Ich sehe da folgende Verbesserungsmöglichkeiten:
* via `useCookies=true` automatisches Handling der Cookies, statt diese manuell zu setzen. Dadurch gehen auch keine Eigenschaften wie secure oder httpOnly verloren.
* Dinge wie Encoding, Bytestreaming, Byte/String Konvertierung ... sollten out-of-the-box kommen.
* Über Eigenschaften wie `BaseAddress`, `DefaultRequestHandlers` kann man sich vielleicht noch etwas Code sparen.

**Comment by atddo** [comment]
Implemented
